Controllers/PagesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebShop.Models.Data;
using WebShop.Models.ViewModels.Pages;

namespace WebShop.Controllers
{
    public class PagesController : Controller
    {
        // GET: Page/Index/page
        [HttpGet]
        public ActionResult Index(string page = "")
        {
            //Set var page is empty or take that if he exists
            if (page == string.Empty)
                page = "home";



            //Create model and data
            PageVM model;
            PageMDL _page;

            //Check what current page is aviliable 
            using (DB db = new DB())
            {
                if (!db.Pages.Any(x => x.Slug.Equals(page)))
                    return RedirectToAction("Index", new { page = "" });
                //Take MDL of this page
                _page = db.Pages.Where(x => x.Slug == page).FirstOrDefault();

                //Set title  of page
                ViewBag.PageTitle = _page.Title;

                //Check on existing sidebar 
                if (_page.HasSidebar)
                    ViewBag.Sidebar = "Yes";
                else
                    ViewBag.Sidebar = "No";

                // Full model by data 
                model = new PageVM(_page);
            }
            //Retutrn View with model
            return View(model);
        }

        // GET: Page/PagesMenuPart
        public ActionResult PagesMenuPart()
        {
            //Innit List of VM
            List<PageVM> pages = new List<PageVM>();

            using (DB db = new DB())
            {
                //Take all pages without HOME
                pages = db.Pages
                          .ToArray()
                          .OrderBy(x => x.Sorting)
                          .Where(x => x.Slug != "home")
                          .Select(x => new PageVM(x)).ToList();
            }

            // Return part of imagine with data 
            return PartialView("PagesMenuPart", pages);
        }

        // GET: Page/SidebarPart
        public ActionResult SidebarPart()
        {
            SidebarVM model;
            //Create and innit model
            using (DB db = new DB())
            {
                SidebarMDL sidebar = db.Sidebars.Find(1);
                model = new SidebarVM(sidebar);
            }
            //Rerturn View with part
            return PartialView("SidebarPart", model);

        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - WEB SHOP</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="/" style="margin-left:10px;">My Shop</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation" style="margin-right:10px;">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText" style="margin-left:10px;">
            <ul class="navbar-nav me-auto ">
                @*@Html.Action("PagesMenuPart", "Pages")*@

                @if (Request.IsAuthenticated)
                {
                    @Html.ActionLink("Logout", "Logout", "Account", null, new { @class = "navbar-text", style = "text-decoration: none;" })
                }
                else
                {
                    @Html.ActionLink("Login", "Login", "Account", null, new { @class = "navbar-text", style = "text-decoration: none;" })
                }

                @if (Request.IsAuthenticated && User.IsInRole("User"))
                {
                    if (ViewBag.Title == "User Profile")
                    {
                        @Html.Action("UserNavPart", "Account", new { area = "", @class = "active" })
                    }
                    else
                    {
                        @Html.Action("UserNavPart", "Account", new { area = "" })
                        @Html.ActionLink("Orders", "Orders", "Account", null, new { @class = "navbar-text", style = "text-decoration: none; margin-left: 10px;" })
                    }
                }
            </ul>

            @if (Request.IsAuthenticated && User.IsInRole("Admin"))
            {
                <span class="navbar-text" style="margin-right:10px;">
                    @Html.ActionLink("Admin Area", "Index", "Dashboard", new { area = "Admin" }, new {@class= "navbar-brand", style = "text-decoration: none;"})
                </span>
            }
            else
            {
                if (ViewBag.Title != "Cart")
                {
                    <span class="navbar-text" style="margin-right:10px;">
                        @Html.Action("CartPart", "Cart")
                    </span>
                }
            }
        </div>
    </nav>



    <div class="container body-content" style="margin-top: 100px;">
        <div class="row">

            <div class="col-sm-12 col-md-3 list-group">
                @Html.Action("CategoryMenuPart", "Shop")
            </div>

            @if (ViewBag.Sidebar == "Yes")
            {
                <div class="col-sm-12 col-md-6">
                    @RenderBody()
                </div>
                <div class="col-sm-12 col-md-3">
                    @Html.Action("SidebarPart", "Pages")
                </div>
            }
            else
            {
                <div class="col-sm-12 col-md-9">
                    @RenderBody()
                </div>
            }

        </div>

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - WEP SHOP</p>
        </footer>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/scripts")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>